spring:
  datasource:
    url: postgresql://postgres:piAJIFggkFhPkGOUVxWYNpQVhdXUDLtb@viaduct.proxy.rlwy.net:36650/railway
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: ecommerceDB

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes